apiVersion: v2
appVersion: 0.1.0
description: Helm chart utilizado no projeto dose na nuvem
# home: 
# icon: 
maintainers:
- name: luizgribeiro 
name: dose-na-nuvem
# sources:
# - https://github.com/
# - https://github.com/
type: application
version: 0.1.0
dependencies:
  - name: opentelemetry-collector
    version: 0.73.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
  - name: jaeger
    version: 0.71.17
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: prometheus
    version: 25.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.60.4
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: dose-toll-station
    version: 0.1.0
